version: "3.8"

services:
  geth:
    image: ethereum/client-go:v1.13.11
    entrypoint: "/bin/sh -c"
    command: [ "apk add -U bash && ./scripts/geth-local-poa-chain.sh" ]
    working_dir: /data
    networks:
      - eth_network
    env_file:
      - './.env.docker'
    volumes:
      - type: bind
        source: ./
        target: /data
    ports:
      - "8546:8546"

networks:
  eth_network:
    name: eth_network
    attachable: true
