version: "3.8"

services:
  gsn_deploy:
    image: ts-opengsn
    profiles: ["deploy"]
    build:
      context: ./
    working_dir: /app/packages/deployer
    command: ["yarn", "deploy", "--network", "dev"]
    networks:
      - eth_network
    volumes:
      - type: bind
        source: ./deploy/config/deploy.ts
        target: /app/packages/deployer/deploy/deploy.ts
      - type: bind
        source: ./deploy/config/hardhat.config.ts
        target: /app/packages/deployer/hardhat.config.ts
      - type: bind
        source: ./deploy/config/deployment-config.ts
        target: /app/packages/deployer/deployments/deployment-config.ts
        # Deployments held in memory.
      - type: tmpfs
        target: /app/packages/deployer/deployments/networks

  gsn_relay:
    image: ts-opengsn
    build:
      context: ./
    working_dir: /app/packages/relay
    stop_grace_period: 3s
    command: [
      "node",
      "./dist/runServer.js",
      "--config",
      "/app/packages/relay/gsn-relay-config.json"
    ]
    networks:
      - eth_network
    ports:
      - "8090:8090"
    volumes:
      - type: bind
        source: ./relay/config/gsn-relay-config.json
        target: /app/packages/relay/gsn-relay-config.json
      - type: bind
        source: ./relay/data
        target: /gsn-data

networks:
  eth_network:
    name: eth_network
    external: true
